services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ads_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: JeqE34Dzka!lkp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network_app

  ads-online:
    build: .
    container_name: ads-online
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: JeqE34Dzka!lkp
      POSTGRES_DB: ads_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      UPLOAD_PATH: /uploads
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/uploads
    networks:
      - network_app

volumes:
  pgdata:

networks:
  network_app:
    driver: bridge
